version: '3'

services:
    db:
        image: postgres
        environment:
            - POSTGRES_PASSWORD
        networks:
            dmcm_net:
                ipv4_address: 172.28.1.1
#    node:
#        image: node:9
#        working_dir: /node
#        command: bash -c "npm install && npm start"
#        volumes:
#            - ./mpages/mpagesjs:/node
#        ports:
#            - "3000:3000"
    webapp:
        build:
            context: .
        image: webapp:dmcm
        environment:
            - DMCM_DATABASE_USER
            - DMCM_DATABASE_PASSWORD
            - DMCM_DATABASE_NAME
            - POSTGRES_PASSWORD
            - DJANGO_SECRET_KEY
        command: python manage.py runserver 0.0.0.0:4313
        ports:
            - 4313:4313
        volumes:
            - .:/opt/dmcm
        working_dir: /opt/dmcm
        depends_on:
            - db
        networks:
            dmcm_net:
                ipv4_address: 172.28.1.2

networks:
    dmcm_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
