# Generated by Django 2.0.7 on 2018-07-08 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=10)),
                ("msg", models.TextField()),
                ("datetime", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["-datetime"]},
        )
    ]
