# Generated by Django 2.1.2 on 2018-10-30 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("timers", "0002_timer_slug")]

    operations = [
        migrations.AlterField(
            model_name="timer",
            name="slug",
            field=models.SlugField(max_length=250, unique=True),
        )
    ]
